import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || '';
const nav = ['Overview', 'Data Quality', 'Segments', 'Model Evaluation', 'Autoresearch', 'Lineage'];

function fmt(n, digits=2) { return n === null || n === undefined ? '—' : Number(n).toFixed(digits); }
function Card({children, className=''}) { return <section className={`card ${className}`}>{children}</section>; }
function Metric({label, value, hint}) { return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>; }

function Scatter({points, selected, onSelect}) {
  const width=620, height=300, pad=28;
  const xs=points.map(p=>p.x), ys=points.map(p=>p.y);
  const minx=Math.min(...xs), maxx=Math.max(...xs), miny=Math.min(...ys), maxy=Math.max(...ys);
  const cx=x=>pad+(x-minx)/(maxx-minx||1)*(width-pad*2);
  const cy=y=>height-pad-(y-miny)/(maxy-miny||1)*(height-pad*2);
  return <div><svg className="scatter" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="PCA customer scatter plot"><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad} className="axis"/><line x1={pad} x2={pad} y1={pad} y2={height-pad} className="axis"/><text x={width/2} y={height-5} className="axis-label">PCA component 1</text><text x="10" y={height/2} className="axis-label" transform={`rotate(-90 10 ${height/2})`}>PCA component 2</text>{points.map((p,i)=><circle key={i} cx={cx(p.x)} cy={cy(p.y)} r={selected===null||selected===p.cluster?4:2} className={`dot c${((p.cluster+10)%8)}`} onClick={()=>onSelect(p.cluster)} />)}</svg><small className="caption">Source: generated model artifact · PCA projection of selected features · click a point to filter its cluster</small></div>;
}

function BarChart({items, valueKey='size', labelKey='cluster', title}) { const max=Math.max(...items.map(x=>x[valueKey]),1); return <div><h3>{title}</h3><div className="bars">{items.map(item=><div className="bar-row" key={item[labelKey]}><span>{item[labelKey]}</span><div className="bar-track"><div className="bar-fill" style={{width:`${item[valueKey]/max*100}%`}}/></div><b>{fmt(item[valueKey],0)}</b></div>)}</div></div>; }

function ProfileCard({p}) { return <div className="profile"><div className="profile-top"><span className={`badge c${p.cluster%8}`}>Cluster {p.cluster}</span><b>{p.persona}</b><small>{fmt(p.share*100,1)}% · {p.size} customers</small></div><div className="profile-grid"><span>Income <b>${fmt(p.means['Annual Income (k$)'],0)}k</b></span><span>Spending <b>{fmt(p.means['Spending Score (1-100)'],0)}/100</b></span><span>Age <b>{fmt(p.means.Age,0)}</b></span></div><p>{p.action}</p></div>; }

function App() {
  const [data,setData]=useState(null), [page,setPage]=useState(()=>new URLSearchParams(window.location.search).get('page')||'Overview'), [cluster,setCluster]=useState(null), [error,setError]=useState('');
  useEffect(()=>{fetch(`${API}/api/dashboard`).then(r=>{if(!r.ok) throw Error('Artifacts are not ready'); return r.json()}).then(setData).catch(e=>setError(e.message))},[]);
  const filtered = useMemo(()=>data?.pca.filter(p=>cluster===null||p.cluster===cluster)||[],[data,cluster]);
  if(error) return <div className="empty"><h1>Customer Intelligence</h1><p>{error}. Run <code>python -m src.pipeline</code>, then refresh.</p></div>;
  if(!data) return <div className="empty"><h1>Customer Intelligence</h1><p>Loading model artifacts…</p></div>;
  const m=data.metrics, profiles=data.profiles, sizes=Object.entries(data.cluster_sizes).map(([cluster,size])=>({cluster,size}));
  return <div className="app"><aside><div className="brand"><div className="brand-mark">CI</div><div><b>Customer Intelligence</b><small>Segmentation lab</small></div></div><div className="nav-label">WORKSPACE</div>{nav.map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)} key={x}><span className="nav-dot"/> {x}</button>)}<div className="sidebar-foot"><span className="status-dot"/> Pipeline healthy<small>v1.0 · seed {data.metadata.seed}</small></div></aside><main><header><div><div className="eyebrow">ANALYTICS ADMIN / {page.toUpperCase()}</div><h1>{page==='Overview'?'Customer segmentation overview':page}</h1><p className="sub">A research-grade view of cluster quality, stability, and marketing actionability.</p></div><div className="header-meta"><span className="source-pill">{data.metadata.demo_fallback?'Demo fallback':'Kaggle CSV'}</span><small>Updated {new Date(data.metadata.generated_at).toLocaleString()}</small></div></header>{page==='Overview'&&<><div className="metrics"><Metric label="CUSTOMERS" value={data.quality.rows} hint="validated rows"/><Metric label="SELECTED CLUSTERS" value={m.cluster_count} hint={data.config.algorithm.toUpperCase()}/><Metric label="SILHOUETTE" value={fmt(m.silhouette,3)} hint="cohesion / separation"/><Metric label="STABILITY" value={`${fmt(m.stability*100,1)}%`} hint="5 repeated fits"/></div><div className="grid-two"><Card><div className="section-head"><div><span className="eyebrow">CLUSTER MAP</span><h2>Customer landscape</h2></div><select value={cluster??''} onChange={e=>setCluster(e.target.value===''?null:Number(e.target.value))}><option value="">All clusters</option>{sizes.map(s=><option key={s.cluster} value={s.cluster}>Cluster {s.cluster}</option>)}</select></div><Scatter points={filtered} selected={cluster} onSelect={setCluster}/></Card><Card><div className="section-head"><div><span className="eyebrow">SEGMENT MIX</span><h2>Customers by cluster</h2></div></div><BarChart items={sizes} title="Customer count by cluster"/><div className="mini-note"><b>Decision signal</b><span>Use the segment cards to translate this model into campaign hypotheses.</span></div></Card></div><Card><div className="section-head"><div><span className="eyebrow">PERSONA SUMMARY</span><h2>Actionable segments</h2></div></div><div className="profiles">{profiles.map(p=><ProfileCard p={p} key={p.cluster}/>)}</div></Card></>}{page==='Data Quality'&&<Quality data={data.quality}/>} {page==='Segments'&&<Segments profiles={profiles} data={data} cluster={cluster} setCluster={setCluster}/>} {page==='Model Evaluation'&&<Evaluation data={data}/>} {page==='Autoresearch'&&<Research data={data}/>} {page==='Lineage'&&<Lineage data={data}/>}</main></div>;
}

function Quality({data}) { return <div className="stack"><Card><div className="section-head"><div><span className="eyebrow">CRISP-DM / DATA UNDERSTANDING</span><h2>Data quality gate</h2></div><span className="good">PASS · {data.source_type}</span></div><div className="quality-grid"><Metric label="ROWS" value={data.rows} hint="input records"/><Metric label="COLUMNS" value={data.columns} hint="schema fields"/><Metric label="DUPLICATE ROWS" value={data.duplicate_rows} hint="removed before modeling"/><Metric label="DUPLICATE IDS" value={data.duplicate_ids} hint="identifier integrity"/></div></Card><Card><h2>Schema and missingness</h2><div className="table"><div className="tr th"><span>Field</span><span>Type</span><span>Missing</span><span>Range</span></div>{data.column_names.map(c=><div className="tr" key={c}><span>{c}</span><span>{data.dtypes[c]}</span><span>{data.missing[c]||0}</span><span>{data.numeric_ranges[c]?`${fmt(data.numeric_ranges[c].min,1)} – ${fmt(data.numeric_ranges[c].max,1)}`:'categorical'}</span></div>)}</div><p className="note">Leakage control: CustomerID is treated as an identifier and excluded from all model features.</p></Card></div>; }
function Segments({profiles,data,cluster,setCluster}) { const p=cluster===null?profiles:profiles.filter(x=>x.cluster===cluster); return <div className="stack"><Card><div className="section-head"><div><span className="eyebrow">SEGMENT EXPLORER</span><h2>Persona profiles</h2></div><select value={cluster??''} onChange={e=>setCluster(e.target.value===''?null:Number(e.target.value))}><option value="">All clusters</option>{profiles.map(x=><option key={x.cluster} value={x.cluster}>Cluster {x.cluster}</option>)}</select></div><div className="profiles">{p.map(x=><ProfileCard p={x} key={x.cluster}/>)}</div></Card><Card><h2>Selected customer records</h2><div className="table"><div className="tr th"><span>Customer ID</span><span>Cluster</span><span>PCA x</span><span>PCA y</span></div>{data.pca.filter(x=>cluster===null||x.cluster===cluster).slice(0,25).map(x=><div className="tr" key={x.customer_id}><span>{x.customer_id}</span><span><span className={`badge c${x.cluster%8}`}>{x.cluster}</span></span><span>{fmt(x.x)}</span><span>{fmt(x.y)}</span></div>)}</div></Card></div>; }
function Evaluation({data}) { const m=data.metrics; return <div className="stack"><Card><div className="section-head"><div><span className="eyebrow">CRISP-DM / EVALUATION</span><h2>Model evidence</h2></div><span className="source-pill">{data.config.algorithm.toUpperCase()}</span></div><div className="quality-grid"><Metric label="SILHOUETTE" value={fmt(m.silhouette,3)} hint="higher is better"/><Metric label="DAVIES–BOULDIN" value={fmt(m.davies_bouldin,3)} hint="lower is better"/><Metric label="CALINSKI–HARABASZ" value={fmt(m.calinski_harabasz,1)} hint="higher is better"/><Metric label="COMPOSITE" value={fmt(m.composite_score,3)} hint="weighted selection score"/></div></Card><Card><h2>Winning configuration</h2><div className="config-grid">{Object.entries(data.config).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><b>{String(v)}</b></div>)}</div><p className="note">The composite score is a multi-objective ranking: silhouette 42%, Davies–Bouldin 18%, Calinski–Harabasz 15%, stability 18%, and cluster balance 7%.</p></Card></div>; }
function Research({data}) { return <div className="stack"><Card><div className="section-head"><div><span className="eyebrow">AUTORESEARCH / HILL CLIMBING</span><h2>Experiment history</h2></div><span className="good">{data.experiments.filter(x=>x.status==='accepted').length} accepted</span></div><div className="table"><div className="tr th"><span>Run</span><span>Status</span><span>Configuration</span><span>Composite</span></div>{data.experiments.map(x=><div className="tr" key={x.run}><span>#{x.run}</span><span className={x.status==='accepted'?'good':x.status==='crash'?'bad':''}>{x.status}</span><span>{x.config.algorithm} · k={x.config.n_clusters} · {x.config.feature_set} · {x.config.scaler}</span><span>{x.metrics?fmt(x.metrics.composite_score,3):'—'}</span></div>)}</div></Card><Card><h2>Search policy</h2><p className="note">Each configuration changes one explicit modeling choice, runs the same deterministic evaluation harness, and is kept only when the composite score improves. The log is the audit trail for accepted and rejected research ideas.</p></Card></div>; }
function Lineage({data}) { return <div className="stack"><Card><div className="eyebrow">CRISP-DM / DEPLOYMENT</div><h2>Artifact lineage</h2><div className="lineage"><div><b>Source</b><span>{data.metadata.source}</span></div><div><b>Preparation</b><span>deduplicate → coerce numeric fields → exclude CustomerID → scale</span></div><div><b>Model</b><span>{data.config.algorithm} / {data.config.feature_set} / {data.config.scaler}</span></div><div><b>Evaluation</b><span>internal metrics + repeated-fit stability + interpretability profiles</span></div><div><b>Generated</b><span>{data.metadata.generated_at}</span></div></div></Card><Card><h2>Responsible use</h2><p className="note">These personas are exploratory marketing hypotheses. They must not be used for credit, eligibility, employment, pricing, or other high-impact individual decisions. Spending score is an assigned score, not a causal measure of customer value.</p></Card></div>; }

createRoot(document.getElementById('root')).render(<App/>);
